language: php
sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
  - 7.1
  - nightly

env:
  - DB=sqlite
  - DB=mysql
  - DB=mysqli

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' && $DB = 'sqlite' ]]; then PHPUNIT_FLAGS="--coverage-clover .clover.xml"; else PHPUNIT_FLAGS=""; fi

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: DB=mariadb MARIADB_VERSION=10.0
      addons:
        mariadb: 10.0
    - php: nightly
      env: DB=mariadb MARIADB_VERSION=10.0
      addons:
        mariadb: 10.0

    - php: 7.1
      env: DB=mariadb MARIADB_VERSION=10.1
      addons:
        mariadb: 10.1
    - php: nightly
      env: DB=mariadb MARIADB_VERSION=10.1
      addons:
        mariadb: 10.1

    - php: 7.1
      addons:
        postgresql: "9.2"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.2
    - php: nightly
      addons:
        postgresql: "9.2"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.2

    - php: 7.1
      addons:
        postgresql: "9.3"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.3
    - php: nightly
      addons:
        postgresql: "9.3"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.3

    - php: 7.1
      addons:
        postgresql: "9.4"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.4
    - php: nightly
      addons:
        postgresql: "9.4"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.4

    - php: 7.1
      sudo: false
      dist: trusty
      addons:
        postgresql: "9.5"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.5
    - php: nightly
      sudo: false
      dist: trusty
      addons:
        postgresql: "9.5"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.5

    - php: 7.1
      sudo: false
      dist: trusty
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.6
    - php: nightly
      sudo: false
      dist: trusty
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      env: DB=pgsql POSTGRESQL_VERSION=9.6

  allow_failures:
    - php: nightly

after_script:
 - if [[ "$PHPUNIT_FLAGS" != "" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
 - if [[ "$PHPUNIT_FLAGS" != "" ]]; then php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi

install:
  - travis_retry composer install

script: ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml $PHPUNIT_FLAGS
